### ISSUE TITLE
XML output support

### ISSUE THREAD

**Issue by annavanbiemen** [neat-php/http-server#11]
The Output class should be able to produce XML responses using either an

- XML string
- SimpleXMLElement instance
- DOMDocument instance

**Comment by annavanbiemen** [comment]
On second thought... automatically detecting the type of XML argument passed adds complexity while the caller can just simply use a single method call to the appropriate API to convert any SimpleXMLElement or DOMDocument instance into a string.

A string-only API should suffice:
```php
public function xml(string $document): Response
```

**Comment by baukevdw** [comment]
Or register an xml handler like this:

```php
$output->register(SimpleXMLElement::class, function (SimpleXMLElement $xml) use ($output): Response {
    return $output->text($xml->asXML())->withContentType('text/xml');
});
```

An XML handler that set's the header would be an useful addition though.

**Comment by annavanbiemen** [comment]
Added the xml handler with just a text/xml Content-Type.
